---
- name: Old Minikube Identifier
  become: true
  find:
    paths: /opt/kubernetes
    pattern: "minikube-\\d+\\.\\d+\\.\\d+$"
    recurse: no
    file_type: directory
    use_regex: yes
    excludes: "minikube-{{ minikube_version }}"
  register: minikube_old_installations

- name: Delete Old Minikube Installations
  become: true
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ minikube_old_installations.files }}"
  when: minikube_old_installations.matched != 0

